### ISSUE TITLE
Shortcut for editing points to nowhere

### ISSUE THREAD

**Issue by TobiMarg** [GioBo/ess-view#4]
The function `ess-view-inspect-df` is currently implementing both viewing and editing dataframes. But the shortcut for editing (still) points to `ess-view-modify-df`.

Changing the concerned line to `(define-key map (kbd "C-x q") 'ess-view-inspect-df)` makes it work.

**Comment by GioBo** [comment]
Wow, thanks for reporting both the bug and the solution, I just pushed the corrected version.
G.
