### ISSUE TITLE
Add matrix support 

### ISSUE THREAD

**Issue by LuhengStat** [GioBo/ess-view#7]
Thanks for the ess-view package. It is very useful for viewing big data frame in ess. 
Could you add a matrix support for ess-view, not only dataframe. I have tried to do these, 
but it can only work in mac.  Thanks.

[ess-view.txt](https://github.com/GioBo/ess-view/files/2000956/ess-view.txt)

**Comment by GioBo** [comment]
New version should work with matrices as well; please check.

**Comment by LuhengStat** [comment]
Thanks. However, the csv file could not be opened with permission problem in the Macos. such as

**The document “15567a4O.csv” could not be opened. You don’t have permission.**  

the older version do not has this kind of problem.

**Comment by GioBo** [comment]
I'm not familiar with Mac Os, but I cannot think of any reason why the 'permission' issue should arise since I've only added a simple statement for matrix support; are you running R as root?

**Comment by LuhengStat** [comment]
Thanks anyway. I think I am not running R as root. However, I think maybe we do not need such a strong permission since the file can be opened before. Maybe latter I will compare the new code with the old version to find the reason. Best.
