### ISSUE TITLE
Does not seem to work when multiple R processes are open

### ISSUE THREAD

**Issue by stefanavey** [GioBo/ess-view#8]
Is this designed to handle multiple R processes? When I have multiple open it does not work as expected and uses the first one opened.  Wanted to check before I dig into the code but I can try to provide a solution if this feature is not implemented

**Comment by GioBo** [comment]
Please try branch **issue#8** which should fix this (if so, I'll merge into master).

**Comment by stefanavey** [comment]
Yes, this fixes the issue.  I tested and it works as expected. It now only gives completion for objects in the ESS process associated with the buffer and opens them as expected.  Thank you!
